# Stage 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ProxyApp/ProxyApp.csproj", "ProxyApp/"]
RUN dotnet restore "ProxyApp/ProxyApp.csproj"
COPY . .
WORKDIR "/src/ProxyApp"
RUN dotnet publish "ProxyApp.csproj" -c Release -o /app/out

# Stage 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
ENV ASPNETCORE_URLS=http://*:$PORT
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "ProxyApp.dll"]
